FROM php:apache-buster
RUN     
COPY yaml-generation /var/www/html/yaml-generation
COPY src /var/www/html/src
RUN cd /var/www/html/yaml-generation && composer install \
--ignore-platform-reqs \
--no-interaction \
--no-plugins \
--no-scripts \
--prefer-dist


RUN pecl channel-update pecl.php.net && pecl install yaml && docker-php-ext-enable yaml
RUN cd /var/www/html && php yaml-generation/generateDimensions.php
workdir /var/www/html
CMD php yaml-generation/generateDimensions.php